var annotated_dup =
[
    [ "ability", "classability.html", "classability" ],
    [ "action", "classaction.html", "classaction" ],
    [ "background", "classbackground.html", "classbackground" ],
    [ "circle", "classcircle.html", "classcircle" ],
    [ "database_not_found", "classdatabase__not__found.html", "classdatabase__not__found" ],
    [ "dialogbox", "classdialogbox.html", "classdialogbox" ],
    [ "end_of_file", "classend__of__file.html", null ],
    [ "figure", "classfigure.html", "classfigure" ],
    [ "game", "classgame.html", "classgame" ],
    [ "invalid_position", "classinvalid__position.html", "classinvalid__position" ],
    [ "leveleditor", "classleveleditor.html", "classleveleditor" ],
    [ "main_menu", "classmain__menu.html", "classmain__menu" ],
    [ "music", "classmusic.html", "classmusic" ],
    [ "npc", "classnpc.html", "classnpc" ],
    [ "picture", "classpicture.html", "classpicture" ],
    [ "player", "classplayer.html", "classplayer" ],
    [ "rectangle", "classrectangle.html", "classrectangle" ],
    [ "sprite", "classsprite.html", "classsprite" ],
    [ "sql", "classsql.html", "classsql" ],
    [ "tile", "classtile.html", "classtile" ],
    [ "unknown_shape", "classunknown__shape.html", "classunknown__shape" ],
    [ "unknown_tile", "classunknown__tile.html", "classunknown__tile" ]
];